#  $LastChangedBy$ - $LastChangedDate$
#
#  Before Editing:
#         If you want to customize any of the dependancies to different paths, DO NOT EDIT THIS FILE!!
#         Instead, create a ibs-project-local.rb, of the same format.  dependancys, libraries, and programs
#         will all be overwritten by any versions found in ibs-project-local.rb.  You will want to
#         specify a new project_root which is on your global-ignores list (I use projects.local,
#         filtered by *.local) instead of constantly differing from the SVN version.
#
#  Note:  Any dependancy, library, or program overridden in ibs-project-local.rb will overwrite
#         the ENTIRE dependancy/library/project, not just the specific options you specify within it!
#

project_root   './projects/'

dependancy( :ruby ) {
	add_include_paths  ENV['RUBYINCLUDE']
	add_library_paths  ENV['RUBYLIB']
	add_library        "msvcr80-ruby#{VERSION.split('.')[0..1].join}.lib"
}

dependancy( :boost ) {
	#  Assumed to be in your IDE paths already (for now)
}

dependancy( :opengl ) {
	#  Assumed to be in your IDE paths already (for now)
	add_library "opengl32.lib"
}

dependancy( :devil ) {
	#  Assumed to be in your IDE paths already (for now)
	add_library "devil.lib"
	add_library "ilu.lib"
	add_library "ilut.lib"
}

dependancy( :sdl ) {
	#  Assumed to be in your IDE paths already (for now)
	add_library "SDL.lib"
}

library( :libindustry ) {
	dependancy :boost
	dependancy :ruby
	sources "industry/**/*.{c,h}pp"
}

program( :unittest ) {
	dependancy :libindustry
	sources "unittest/**/*.{c,h}pp"
	msvc_warning_level  4
	msvc_supress_warnings  4100, 4512, 4127, 4189, 4701, 4180, 4224
}

program( 'demo-opengl1' ) {
	dependancy :libindustry
	dependancy :sdl
	dependancy :opengl
	dependancy :devil
	sources "demos/opengl1/**/*.{c,h}pp"
	msvc_supress_warnings  4267, 4312
}

program( 'demo-opengl2' ) {
	dependancy :libindustry
	dependancy :sdl
	dependancy :opengl
	dependancy :devil
	sources "demos/opengl2/**/*.{c,h}pp"
	msvc_supress_warnings  4244, 4267
}

script( :ibs , :ruby ) {
	sources "ibs-lib/**/*.rb"
	start   "ibs-lib/ibs.rb"
}
